import { initializeFirebaseApp } from "@/lib/firebase"
import { Providers } from "../../lib/providers"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
initializeFirebaseApp()
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
